### ISSUE TITLE
browZer support - router WebSocket edge binding

### ISSUE THREAD

**Issue by qrkourier** [openziti/helm-charts#114]
Ziti Router can provide a `wss://` listener for browZer clients. Improve the router chart to support this feature and provide a config sample or guide in the chart README so it'll be auto-published in Ziti docs.

**Comment by thiagosestini** [comment]
looking at the Helm charts it seems this is really not currently supported:

https://github.com/openziti/helm-charts/blob/537e0bbd35a91f254aec9dfe11ab79c30d5e4627/charts/ziti-router/templates/configmap.yaml#L135

It would be an useful addition to run BrowZer with Kubernetes based deployments.
