### ISSUE TITLE
ziti-router - fresh install fails

### ISSUE THREAD

**Issue by marvkis** [openziti/helm-charts#141]
Hi,

I just tried to install a new ziti-router instance on a fresh node, but the Helm installation failed:

```
Helm release "openziti/core-router" was created, but failed to initialize completely. Use Helm CLI to investigate.: failed to become available within allocated timeout. Error: Helm Release openziti/core-router: context deadline exceeded
```

I started digging into it a bit, and from what I see:

* The router pod for the deployment is stuck in *ContrainerCreating* state due to:
```
  Warning  FailedMount  5s (x15 over 14m)    kubelet            MountVolume.SetUp failed for volume "ziti-router-identity" : secret "core-router-identity" not found
```
* From what I understand there is a *post-install hook* here https://github.com/openziti/helm-charts/blob/main/charts/ziti-router/templates/post-install-hook.yaml responsible for creating the *-identity* secret

AFAIK the post-install hook get's executed *after* all other resources are created and ready - but the deployment won't get ready as it's missing the secret. A chicken/egg issue?

**Comment by marvkis** [comment]
🤔 I'm tryng to deploy the helm chart via pulumi. Maybe pulumi is doing here something special. Will try to install it via helm/cli later to double check.... tried to fiddle around with some *skipAwait* options https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/#inputs but this didn't change things.

**Comment by qrkourier** [comment]
Did the post-install Job pod log anything interesting? It should step from Running to Terminated quickly after creating the Secret named after the Helm release.

**Comment by marvkis** [comment]
The problem is - I don't see the post-install job starting. I think it's due to the deployment stuck in ContainerCreating... I'll try it with the normal helm command to check what happens...

**Comment by qrkourier** [comment]
I bet Pulumi is sending the equivalent of `helm install --no-hooks`. I found Terraform did that, and had to add a param to enable life cycle hooks. That would explain both why you're not seeing the Job pod, and why the secret doesn't exist, because it's created by the post-install life cycle hook Job.

**Comment by marvkis** [comment]
OK, a normal installation works, but with the `--wait' option it has the same behaviour I see when installing via pulumi - the post-install job is not starting...

**Comment by qrkourier** [comment]
That matches what I found for Terraform in https://github.com/openziti-terraform-modules/terraform-k8s-openziti-router/blob/main/main.tf#L33C31-L33C31

**Comment by marvkis** [comment]
Okay, got it working with pulumi. There is a `skipAwait` option (that has to be set to *true* - 🙈 - its too late for clear thoughts here 😉 )... Now it behaves like helm without --wait. I found no documentation for pulumi helm, but in the common kubrnetes docu. Maybe it works on all kubernetes related resources. https://www.pulumi.com/registry/packages/kubernetes/installation-configuration/#annotations

I think we can close this right now. Thank's for your help!

**Comment by marvkis** [comment]
Hi @qrkourier ,

a few final thoughts:
* To resolve this install `--wait` situation we could use a *pre-install* hook instead of a *post-install*
* The pre-install would suffer from a missing router-jwt secret containing the enrollmentJwt. But as the enrollmentJwt is single-use and time-constrainted: Why should we keep the JWT in a secret and not inject it to the pre-install hook? The hook will run once, use the JWT and is gone - also the JWT. 🤔 damn, forgot the serviceaccount. 

Two further questions:
* is the PVC currently in use? AFAIK I had it initially for the identity - but it might be obsolete now?
* How does 'identity-renewal' fit into the secret approach - what happens when the identity expires and has to be refreshed?

**Comment by qrkourier** [comment]
@marvkis Thanks for thinking about this with me! Let's consider your questions and ideas in light of this forthcoming change to enable the router to auto-renew its certificates: https://github.com/openziti/helm-charts/pull/140. That PR could merge as written, but I thought best to wait for 0.30.4 that resolves a race condition related to cert renewal, though it's unlikely to manifest during a normal auto-renewal at interval.

That's true about the JWT. It's only consumed by the install and upgrade life cycle hooks, so it doesn't need to be persisted. We could assume it's present as an input value and not store it. About the SA, I see why we'd need to make some adjustments to the script that's run by the life cycle hook jobs that use the SA, but that doesn't seem prohibitive considering the benefit of eliminating the `--wait` snag for systems that wrap Helm.

The PVC is used in the current release only when a controller endpoint update event is consumed or when there are multiple controllers (HA). In the PR I linked above this expands the PVC to also store the leaf certs and trust anchor bundle, in addition to that ./endpoints text file adjacent the router's config YAML.

identity-renewal - also addressed in the linked PR, which retains the private key in the identity secret (doesn't change during renewal), and moves the leaf certs to the PVC.
