### ISSUE TITLE
zrok chart is non-functional

### ISSUE THREAD

**Issue by joshuarestivo** [openziti/helm-charts#161]
Based on commit history and the current state of main, this chart appears to be right in the middle of a refactor. From what I gather, everything is in the process of being separated into separate  controller/frontend files. I knocked out about five issues just to see if I could get it going but I would need to understand some intent before proceeding.

Also, I don't want to do a bunch of work if someone has already continued further than what's represented in the github repo.

Is it possible to get status on this? If I can get a braindump of the desired direction, I'd help finish up the work.

**Comment by qrkourier** [comment]
I believe you're the tip of the spear there. I'm sorry to learn that I failed to keep my breaking changes contained on a branch. I've been trying to claw my way back to that effort!

I'd love your help with the zrok chart. I seem recall that I  finished adapting the chart to the zrok 0.4 spec when I got sidetracked. I will check for unfinished branches and report back here. 

Are you planning to run ziti in k8s too? Things snowballed a bit when I started looking at improving the controller chart to create a default router. 

What's your preferred config mgmt to drive Helm values for a complex chart like this? I've experimented with Terraform over here: https://github.com/openziti-terraform-modules/terraform-lke-ziti/tree/main/plan-50-zrok

**Comment by qrkourier** [comment]
Confirmed. The chart in main was working old zrok 0.3, but everything is in a 0.4 world now. The shape of the deployment is the same, but now there's optional extra stuff like metrics and limits. Would you more inclined toward all the things or a minimal tiny scale zrok to get going?

**Comment by qrkourier** [comment]
I cleanup up the refactor branches to separate this issue (adapt to zrok 0.4 spec) from [the issue about creating a default router when the controller chart is installed](https://github.com/openziti/helm-charts/issues/108).

This should help expedite finishing the work to bring the zrok chart up to date for 0.4.

**Comment by qrkourier** [comment]
@joshuarestivo the linked branch on this issue is ready for review ([readme](https://github.com/openziti/helm-charts/tree/bump-zrok/charts/zrok#readme)). I've got it deploying zrok 0.4 locally and in CI. Next steps include testing TLS termination, metrics, and limits. Any further changes can go in new branches.
