### ISSUE TITLE
ziti-edge-tunnel: ImagePullBackOff upgrading the image

### ISSUE THREAD

**Issue by mjtrangoni** [openziti/helm-charts#180]
Hi @qrkourier,

We face an issue upgrading the *ziti-edge-tunnel* helm chart, where it sometimes works, and sometimes not as the tunnel was already killed and there is no way of pulling the new image.

**DISCLAIMER**: We mirror the container registries as described [here](https://docs.k3s.io/installation/private-registry#mirrors) via the very same tunnel, because the clusters does not have internet.

The first proposal would be to switch `values.image.pullPolicy` from *Always* to *IfNotPresent* [here](https://github.com/openziti/helm-charts/blob/main/charts/ziti-edge-tunnel/values.yaml#L7).

The second one, and the more interesting one, would be adding some kind of pre-pull mechanism, which would be default disabled of course. The options I see here, but I still not tested it as I want to hear your thoughts, are:

1. A fake initContainer which pulls the very same image.
1. Add a pre-puller as DaemonSet as described [here](https://jacobtomlinson.dev/posts/2023/quick-and-dirty-way-to-pre-pull-container-images-on-kubernetes/).

Let me know what you think, and I can start working this out.

Thank you!

**Comment by qrkourier** [comment]
> The first proposal would be to switch values.image.pullPolicy from Always to IfNotPresent [here](https://github.com/openziti/helm-charts/blob/main/charts/ziti-edge-tunnel/values.yaml#L7).

This is a fine default for the chart: `IfNotPresent`. You're working around the issue by setting input `values.image.pullPolicy` to `IfNotPresent`?

As I understand it, the second proposal is a new, optional daemonset that can be enabled by setting an input value to the chart. Its purpose is to detect the specified container image for the ZET release and pull it to every worker node in advance, solving one potential issue for users of the ZET daemonset chart: the ZET daemonset is scheduled on a node that doesn't already have a copy of the image and isn't able to pull from a remote registry directly.

Such a pre-puller daemonset could be helpful and become a pattern across all OpenZiti charts, making them more immediately usable in a scenario where nodes are some definition of "airgapped," yes?

**Comment by mjtrangoni** [comment]
@qrkourier I invested some time on this topic, and there is no encapsulated way of doing this well or better, as Helm does not support waiting on a dependent `subchart`. Another limitation I found was that we can't pass the `appVersion` variable value from the parent chart to the subchart to define the tunneler image version only once.

I would like create a slim helm chart for doing the "pre-pull" task, and host it here if you agree/ would like to. If yes, let me know what is you preferred helm chart name 😆.  
Then the person having this kind of issue in an *airgapped* environment like me, would have to take care of it and manage it over another automation tool, like flux, which is what I use currently.

Thoughts?

**Comment by qrkourier** [comment]
I would like to study your solution! Is the new chart necessarily bespoke to ziti? If not, then I'd prefer it to be generic and shared with the wider K8s community through a platform like Artifact Hub than to add it to this repo.

**Comment by mjtrangoni** [comment]
@qrkourier fair! I will host it on our side, as it is not directly required by ziti directly. I guess we can close this issue, or should I document the case in the README?

**Comment by qrkourier** [comment]
@mjtrangoni That's generous. Thank you. Please mention this case in the README!
