### ISSUE TITLE
additionalArgs rendering defect

### ISSUE THREAD

**Issue by qrkourier** [openziti/helm-charts#225]
@marvkis  reported https://github.com/openziti/helm-charts/commit/a3ad8ecc7cbda7e16d76f4cba3c6751685ecf718#commitcomment-143157974

I agree with the suggestion of adding the check for non zero length list. 

We also need to figure out how the CI check succeeded since this appears to break the chart with default input for the new value in at least one case.

**Comment by marvkis** [comment]
PR #227 fixes this issue ;)
